CREATE DATABASE IF NOT EXISTS blockdrive CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE blockdrive;

CREATE TABLE IF NOT EXISTS register (
  U_id VARCHAR(16) NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  subscription_plan VARCHAR(20) NOT NULL DEFAULT 'free',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS subscriptions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  U_id VARCHAR(16) NOT NULL,
  plan VARCHAR(20) NOT NULL,
  upload_limit INT UNSIGNED NOT NULL,
  uploads_used INT UNSIGNED NOT NULL DEFAULT 0,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_subscriptions_user_status (U_id, status, end_date),
  CONSTRAINT fk_subscriptions_user FOREIGN KEY (U_id) REFERENCES register(U_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS files (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  cid VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  upload_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_files_email_date (email, upload_date)
) ENGINE=InnoDB;
